import GlobalStyles from "@/GlobalStyles";
import Head from "next/head";
import Header from "./Header";

export default function HeadPageInfo() {
  return (
    <>
      <Head>
        <title>MKS Desenvolvimento de sistemas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyles />
    </>
  )
}